[package]
name = "http"
version = "0.2.3"
authors = ["KizzyCode Software Labs./Keziah Biermann"]

[dependencies]
io = { git = "https://github.com/KizzyCode/io" }
etrace = { git = "https://github.com/KizzyCode/etrace" }